name: prototype_advance
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter:
  get:
  dio:
  http:
  flutter_screenutil:
  proste_bezier_curve:
  hive:
  path_provider:
  location: 
  intl:
  pull_to_refresh: 
  geolocator:
  sunrise_sunset:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

